services:
  database:
    restart: always
    image:  postgres:15.4-bullseye
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    networks:
      - back
    volumes:
      - postgres-data:/var/lib/postgresql/data
  back:
    restart: always
    build:
      context: ./
      target: back-dev
    volumes:
      - ./packages:/home/user/node/packages
    depends_on:
      - database
    networks:
      - front
      - back
  front:
    restart: always
    build:
      context: ./
      target: front-dev
    volumes:
      - ./packages:/home/user/node/packages
    depends_on:
      - back
    ports:
      - 8080:8080
    networks:
      - front

volumes:
  postgres-data:
networks:
  back:
  front: